# Dockerfile
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11.9

COPY ./app /main

# 
COPY ./requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]